drop table if exists users, items, bookings, comments, requests;

create table if not exists users (
    id integer generated by default as identity primary key,
    name varchar not null,
    email varchar not null unique
);

create table if not exists requests (
    id integer generated by default as identity primary key,
    description varchar not null,
    user_id integer not null references users(id),
    creation_time timestamp without time zone not null
);

create table if not exists items (
    id integer generated by default as identity primary key,
    name varchar not null,
    description varchar not null,
    available bit not null,
    user_id integer not null references users(id),
    request_id integer references requests(id)
);

create table if not exists bookings (
    id integer generated by default as identity primary key,
    start_date timestamp without time zone not null,
    end_date timestamp without time zone not null,
    item_id integer not null references items(id),
    user_id integer not null references users(id),
    status varchar not null
);

create table if not exists comments (
    id integer generated by default as identity primary key,
    text varchar not null,
    creation_time timestamp without time zone not null,
    item_id integer not null references items(id),
    user_id integer not null references users(id)
);

